# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enhancement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_imgEnhancement(object):
    def setupUi(self, imgEnhancement):
        imgEnhancement.setObjectName("imgEnhancement")
        imgEnhancement.resize(1136, 578)
        self.gridLayout = QtWidgets.QGridLayout(imgEnhancement)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(imgEnhancement)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.graphicsView = QtWidgets.QGraphicsView(imgEnhancement)
        self.graphicsView.setMinimumSize(QtCore.QSize(500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.enhance_pushButton = QtWidgets.QPushButton(imgEnhancement)
        self.enhance_pushButton.setMinimumSize(QtCore.QSize(100, 20))
        self.enhance_pushButton.setObjectName("enhance_pushButton")
        self.horizontalLayout_3.addWidget(self.enhance_pushButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(imgEnhancement)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.graphicsView_2 = QtWidgets.QGraphicsView(imgEnhancement)
        self.graphicsView_2.setMinimumSize(QtCore.QSize(500, 500))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_2.addWidget(self.graphicsView_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(2, 4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.enhance_method = QtWidgets.QComboBox(imgEnhancement)
        self.enhance_method.setEnabled(True)
        self.enhance_method.setMinimumSize(QtCore.QSize(120, 30))
        self.enhance_method.setObjectName("enhance_method")
        self.horizontalLayout_4.addWidget(self.enhance_method)
        self.selected_model = QtWidgets.QComboBox(imgEnhancement)
        self.selected_model.setMinimumSize(QtCore.QSize(200, 30))
        self.selected_model.setObjectName("selected_model")
        self.horizontalLayout_4.addWidget(self.selected_model)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.save_button = QtWidgets.QPushButton(imgEnhancement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(120, 30))
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_4.addWidget(self.save_button)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)

        self.retranslateUi(imgEnhancement)
        QtCore.QMetaObject.connectSlotsByName(imgEnhancement)

    def retranslateUi(self, imgEnhancement):
        _translate = QtCore.QCoreApplication.translate
        imgEnhancement.setWindowTitle(_translate("imgEnhancement", "Enhancement"))
        self.label.setText(_translate("imgEnhancement", "原图"))
        self.enhance_pushButton.setText(_translate("imgEnhancement", "处理"))
        self.label_2.setText(_translate("imgEnhancement", "输出"))
        self.save_button.setText(_translate("imgEnhancement", "保存图片"))
